services:
  backend:
    build:
      context: ./Server
    ports:
      - "5000:5000"
    env_file:
      - ./Server/.env
    volumes:
      - ./Server:/app
      - /app/node_modules
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./Client
    ports:
      - "3000:3000"
    volumes:
      - ./Client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network: