# version: '3.8'

# services:
#   backend:
#     build:
#       context: ./Server
#     ports:
#       - "5000:5000"
#     env_file:
#       - ./Server/.env
#     volumes:
#       - ./Server:/app
#       - /app/node_modules
#     depends_on:
#       - mongo
#     networks:
#       - app-network
#     restart: unless-stopped

#   frontend:
#     build:
#       context: ./Client
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./Client:/app
#       - /app/node_modules
#     stdin_open: true
#     tty: true
#     depends_on:
#       - backend
#     networks:
#       - app-network
#     restart: unless-stopped

#   mongo:
#     image: mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
#     networks:
#       - app-network

#   prometheus:
#     image: prom/prometheus:latest
#     container_name: prometheus
#     ports:
#       - "9091:9090"
#     volumes:
#       - ./prometheus.yml:/etc/prometheus/prometheus.yml
#       - prometheus_data:/prometheus
#     command:
#       - '--config.file=/etc/prometheus/prometheus.yml'
#     networks:
#       - app-network

#   grafana:
#     image: grafana/grafana:latest
#     container_name: grafana
#     ports:
#       - "3001:3000"
#     volumes:
#       - grafana_data:/var/lib/grafana
#     depends_on:
#       - prometheus
#     networks:
#       - app-network

# volumes:
#   mongo-data:
#   prometheus_data:
#   grafana_data:

# networks:
#   app-network:
version: "3.8"

services:
  # Le service 'mongo' a été supprimé car vous utilisez MongoDB Atlas.

  backend:
    build: ../Server
    container_name: backend
    restart: unless-stopped
    # On passe la variable d'environnement directement. Docker-compose la lira depuis un fichier .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "5000:5000"
    networks:
      - app-network
    # Les volumes de montage de code source ne sont pas nécessaires car l'image contient déjà le code.

  frontend:
    build: ../Client
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    stdin_open: true
    tty: true

  prometheus:
    container_name: prometheus
    restart: unless-stopped
    build:
      context: .
      dockerfile: prometheus.dockerfile
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    volumes:
      - prometheus_data:/prometheus
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  # Le volume mongo-data n'est plus nécessaire.